### ISSUE TITLE
Slice Builder Tests

### ISSUE THREAD

**Issue by yaxue1123** [fabric-testbed/fabric-portal#175]
@paul-ruth @ibaldin Please test portal slice builder via Experiments -> My Slices -> “Create Slice” and document any functional bug or usability concern in the comments here. 

**Feedback from Paul:**

- [ ] VM could be empty, doesn't have to include at least one component; [TODO in 1.3](https://github.com/fabric-testbed/fabric-portal/issues/178)
- [x] Add "Delete" button on the slice viewer; 
- [ ] Add a "Delete All Slices" button on the My Slices section; - [TODO in 1.3](https://github.com/fabric-testbed/fabric-portal/issues/179)
- [ ] Update component wording to be consistent with FABLib. - [TODO in 1.3](https://github.com/fabric-testbed/fabric-portal/issues/177)

**Delete A Slice**:

- [x] Add Delete button in Slice Viewer for slices in state "StableOK" and "StableError";
- [x] Add confirmation modal after user clicks the delete button;
- [x] Change filter on My Slices from "Include Dead Slices" to "Include Dead/ Closing Slices";

@yaxue1123 will categorize the issues, update the slice builder for release 1.2, and plan for any significant improvement request for release 1.3.

@yaxue1123 need also write slice builder documentation:

- [x] User Guide, posted to Knowledge Base -> Topic: Technical User Guide?
- [x] Slice Builder API Call Flow Diagram;
- [x] Slice Builder Component Tree Diagram;
- [ ] Wrap up requests for Orchestrator/ FIM? regarding the slice model (e.g. specify source -> target direction for links, adding layout properties for nodes, etc.) [TODO in 1.3](https://github.com/fabric-testbed/fabric-portal/issues/180)

**Comment by yaxue1123** [comment]
![Slice Builder API Call Flow Diagram](https://user-images.githubusercontent.com/37635744/168729555-01ca3d8d-3442-433e-b7b9-8088a43ba996.png)

**Comment by yaxue1123** [comment]
![Slice Builder Diagrams - Component Tree - v1](https://user-images.githubusercontent.com/37635744/169152300-1d29d1e8-bd15-40a1-89a3-93179985d3d7.png)

**Comment by paul-ruth** [comment]
For the "delete" and "delete all" buttons it should pop a box that requires the user to confirm the delete.
