### ISSUE TITLE
UX Improvements for Slice Builder

### ISSUE THREAD

**Issue by yaxue1123** [fabric-testbed/fabric-portal#198]
Laura tried the Portal Slice Builder as a new user, found usability issues and provided valuable suggestions. After discussion, we decided to make the following updates and improvements UI-wise.

**Overall**

- [x] Change the page header from `New Slice` to `Slice Builder`;
- [x] Change `Project Tags` to `Project Permissions` in Slice Builder and Project page;
- [x] Update the page layout. Ideally the slice graph canvas should take up all the right side, while step blocks are on the left to fit users' reading direction patterns. The Input Slice Information step with the Create Slice button should be moved to the end. Step1. Select Project -> Step 2: Add Nodes and Components -> Step3: Add Network Service -> Step 4: Input Slice Information;
- [x] Make icons in callout messages consistent with the callout message color: -> _removed the warning icons in all callout messages, to be consistent with the other form warning messages across portal._
- [x] Add more helper text/ change jargon name based Laura's comments below.
- [x] Add links to specific guide article sections for each step header.

**Step by Step**

_Add Nodes and Components_

- [x] Before user chooses a site, show the available resources for the whole testbed;
- [x] Mapping site acronym to site name in the dropdown list to be consistent with the portal resource map -> _Discussed with Ilya: we should get the experimenters to get used to site acronyms and the longer name is more for semantic clarity. So I kept using site acronyms in the site dropdown list but add a full name above the site availability table._ ([Related Issue](https://github.com/fabric-testbed/fabric-portal/issues/204))
- [x] Change "Core" to "Cores", add units to RAM and Disk;
- [x] Change `Image Type` to `Image Format`;
- [x] Change `Image Ref` to `OS Image`; and added mapping to the dropdown choices (see comment below);
- [x] + component: change to a way that user only need to click the + button to add another component -> _After consideration, I think it's still necessary to use the + button to add a component, and X button to delete a component. But I add a message `No component added. Please click the + button to add a component.` to remind users to be aware of clicking the + button is required to add a component. And the original warning message of choosing component type/ model or inputing component name is hidden unless the user inputs a non-unique component name within the same node(`Component name should be unique in the same node.`)_

_Slice Canvas_

- [x] Modify the sensitivity by user's mouse scroll;
- [x] Add a 'Reset Layout' button to change the topology graph to its original layout and position;
- [x] Replace all words `Graph` with `Topology`.

_Add Network Service_ 

- [x] Move the "Click on the graph to select connection points." into a callout message similar to the other warning messages/ change the wording to be clearer for users to understand;

**Functional Update**

- [x] Allow adding a VM without components. ([Related Issue](https://github.com/fabric-testbed/fabric-portal/issues/178))

**Decided to Not Change**

- Add red * mark to all required field for consistency (indicating red * as 'required' in one place and use it across the form fields): _I decided to not add this * because basically every field in the forms is required and adding red * to all of them will take up unnecessary space/ make the UI busier. The reason I add “*required” to the slice name/ ssh key fields is due to the comparison of optional field: Lease End Time (used to be preset to current time with a label “Optional. Default end time is 24 hours upon creation if not selected.”) And I’ve changed it to be set as 24 hours later than current time by default and removed the “Optional. Xxx” message._
- Divide the first warning message for node information into two, each closely below the form fields it's related to (one warning below Site/ Node Type/ Node Name, shown by default; the other hidden by default but shown when user inputs invalid core/ ram/ disk values): _To save vertical space, I changed the layout a bit: the previous three rows are compressed to two rows (1: site + node type + node name; 2: cores + ram + disk + image format + os image), and also added light grey background color to this section. This part is considered as a whole and the warning message sits closely with these fields. I think it’s reasonable to use one warning message block to 1. Save vertical space; 2. The message is targeted on prompting users input correct data for the node information, which are right above this message by two rows._ 

**TODO: Make the difference of disabled/ active buttons more obvious**
- How to Make the difference between disabled/ active buttons more obvious (e.g. Laura recommends pale gray to green instead of light green to green):  _I searched for related UI/ UX articles and it is proven that the good practice is to use opaque version of the primary color instead of graying out the disabled button. Actually portal is using Bootstrap’s default styling for disabled button, and Bootstrap is practicing the better UX rule, so I decide to keep current styling until there is a better solution (e.g. how to make the workflow not use disabled button but still prevent user’s error effectively)._

**TODO: Model Availability**

- Fraida's question: I can specify the “model” type of a component but I don’t know if there is anywhere that shows that level of granularity - e.g. I can see a site has 3 GPUs but not what model they are. So I don’t know if the resources I’m requesting will be available: **_After discussion with Laura and Ilya, this issue is something we need to work on in both portal and FABLib - not allowing infeasible slice requests._**

**Comment by yaxue1123** [comment]
```
 OsImageMapping = {
    "default_centos8_stream": "CentOS Stream 8",
    "default_centos9_stream": "CentOS Stream 9",
    "default_centos_7": "CentOS 7",
    "default_centos_8": "CentOS 8",
    "default_debian_10": "Debian 10",
    "default_fedora_35": "Fedora 35",
    "default_rocky_8": "Rocky Linux 8",
    "default_ubuntu_18": "Ubuntu 18",
    "default_ubuntu_20": "Ubuntu 20",
    "default_ubuntu_21": "Ubuntu 21",
    "default_ubuntu_22": "Ubuntu 22",
  }
```

**Comment by yaxue1123** [comment]
For **Step 1: Select Project**, user need hover on each project permission to view the details:
![Updated Version](https://user-images.githubusercontent.com/37635744/181612782-db682e99-2ff8-4244-b05a-9fa18ac6a3e9.png)

This change helps save space vertically for moving all toolbars to the left and leave the right side for topology canvas.
![Legacy Version](https://user-images.githubusercontent.com/37635744/181613087-d7b9221d-ef5d-44e0-b5a2-77d9cab5c7b5.png)
