### ISSUE TITLE
Summary of Updates for Release 1.3 

### ISSUE THREAD

**Issue by yaxue1123** [fabric-testbed/fabric-portal#207]
**To deploy in release 1.3**

- [x] Integrated Portal with Core API: replaced PR/ UIS with Core API, replaced mock data for facility updates/ maintenance notices with API data ([ticket](https://github.com/fabric-testbed/fabric-portal/issues/193))
- [x] Modified Portal based on updated Orchestrator API and CM API ([ticket](https://github.com/fabric-testbed/fabric-portal/issues/206))
- [x] Updated toast error messages with error details in API response of Core API/ Orchestrator API and CM API ([ticket](https://github.com/fabric-testbed/fabric-portal/issues/186))
- [x] Improved UI/ UX for slice builder based feedback/ suggestions from Laura and Fraida (Mostly done. TODO: 1. Laura's lists for items to add helper text; 2. update the documentation from learn site then add links for each step header in Slice builder UI.) ([ticket](https://github.com/fabric-testbed/fabric-portal/issues/198))
- [x] Updated Slice Builder validation to allow empty VM without components ([ticket](https://github.com/fabric-testbed/fabric-portal/issues/178))
- [x] Updated Signup page - Step 1 ([ticket](https://github.com/fabric-testbed/fabric-portal/issues/205))
- [x] Updated site acronym to name mapping ([ticket](https://github.com/fabric-testbed/fabric-portal/issues/204)) and FABRIC Topology Map ([ticket](https://github.com/fabric-testbed/fabric-portal/issues/192)) based latest FABRIC Site Information ([List of Hanks](https://fabric-testbed.atlassian.net/wiki/spaces/FP/pages/168624158/List+of+Hanks+FABRIC+Site+Information))

**Updates already been deployed to production**

- [x] Added static Contact Us page([ticket](https://github.com/fabric-testbed/fabric-portal/issues/191))
- [x] Added Jira links for account issues, project lead requests, project permissions requests, and storage requests ([ticket](https://github.com/fabric-testbed/fabric-portal/issues/199))
- [x] Added Trusted CI Badge to portal footer ([ticket](https://github.com/fabric-testbed/fabric-portal/issues/202))

**Documentation Update to be Consistent with the New Release**
- [x] Update relevant Knowledge Base articles (step-by-step guide articles, screenshots, etc.)
- [x] Update Design documentation in Google drive
- [x] Update Github repo `README.md`
