### ISSUE TITLE
UI Updates based on feedback from Rel 1

### ISSUE THREAD

**Issue by yaxue1123** [fabric-testbed/fabric-portal#90]
**Project Page**

- [x] Add a back button on the right of the project name which leads to the project list page ([issue 69](https://github.com/fabric-testbed/fabric-portal/issues/69));
- [x] Enable search by description/ facility/ project creator function to the project list search bar ([issue 83](https://github.com/fabric-testbed/fabric-portal/issues/83));

**User Profile Page**

- [x] Replace the [red cross icon](https://fontawesome.com/v5.15/icons/times?style=solid) with [ban icon](https://fontawesome.com/v5.15/icons/ban?style=solid) to reduce confusion; Add tooltips for "Facility Operator" and "Project Lead" with question icons to let users hover and see help explanation texts ([issue 
68](https://github.com/fabric-testbed/fabric-portal/issues/68));
- [x] Change "My Roles" section name to "My Roles and Projects"([issue 84](https://github.com/fabric-testbed/fabric-portal/issues/84));

**Signup Workflow**

- [x] Updated the redirection text for non-active users trying login. ([issue 85](https://github.com/fabric-testbed/fabric-portal/issues/85))

**Comment by yaxue1123** [comment]
Related issue from software planning repo: https://github.com/fabric-testbed/software-planning/issues/53
